name: Pylint

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        if: always()
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      if: always()
      run: |
        pip install pylint
        pylint $(git ls-files '*.py')
    - name: Test with pytest
      if: always()
      run: |
        pip install pytest
        pytest $(git ls-files '*.py') --doctest-modules

